In [42]:
import pandas as pd
import requests
from pprint import pprint
import time as T
from datetime import datetime

In [43]:
#table_1 = pd.read_csv("Table 1.csv")
#table_2 = pd.read_csv("Table 2.csv")
#table_3 = pd.read_csv("Table 3.csv")
#table_4 = pd.read_csv("Table 4.csv")
#table_5 = pd.read_csv("Table 5.csv")
#table_6 = pd.read_csv("Table 6.csv")

In [44]:
table_1 = pd.read_csv("Table 1.csv", parse_dates = [0])
table_2 = pd.read_csv("Table 2.csv", parse_dates = [0])
table_3 = pd.read_csv("Table 3.csv", parse_dates = [0])
table_4 = pd.read_csv("Table 4.csv", parse_dates = [0])
table_5 = pd.read_csv("Table 5.csv", parse_dates = [0])
table_6 = pd.read_csv("Table 6.csv", parse_dates = [0])

In [45]:
table_1['Full Date'] = table_1['Full Date'].dt.strftime('%Y-%m-%d')
table_2['Full Date'] = table_2['Full Date'].dt.strftime('%Y-%m-%d')
table_3['Full Date'] = table_3['Full Date'].dt.strftime('%Y-%m-%d')
table_4['Full Date'] = table_4['Full Date'].dt.strftime('%Y-%m-%d')
table_5['Full Date'] = table_5['Full Date'].dt.strftime('%Y-%m-%d')
table_6['Full Date'] = table_6['Full Date'].dt.strftime('%Y-%m-%d')

In [46]:
#table_1.head()

In [47]:
merged = pd.concat([table_1,table_2,table_3,table_4,table_5,table_6], axis=0)

In [48]:
# Step one: fill in blanks for Tampa Bay

In [49]:
empty_locations = merged[merged.Latitude.isnull()]
empty_locations

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
20,2008-09-14,4:05PM,1600,15,2,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate or heavy rain shower'},71.0
44,2008-09-28,1:02PM,1300,12,4,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,90.0,{'value': 'Patchy rain possible'},46.0
62,2008-10-12,1:02PM,1300,12,6,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,84.0,{'value': 'Moderate or heavy rain shower'},37.0
2,2008-10-19,8:23PM,2000,19,7,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,74.0,{'value': 'Light rain shower'},62.0
42,2008-11-16,1:02PM,1300,12,11,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,86.0,{'value': 'Overcast'},90.0
67,2008-11-30,1:02PM,1300,12,13,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,76.0,{'value': 'Sunny'},0.0
33,2008-12-21,1:02PM,1300,12,16,Tampa Bay,Buccaneers,Chargers,NaN,NaN,84.0,{'value': 'Sunny'},10.0
45,2008-12-28,1:02PM,1300,12,17,Tampa Bay,Buccaneers,Raiders,NaN,NaN,85.0,{'value': 'Sunny'},15.0
68,2009-09-13,1:03PM,1300,12,1,Tampa Bay,Buccaneers,Cowboys,NaN,NaN,86.0,{'value': 'Cloudy'},75.0
90,2009-09-27,1:00PM,1300,12,3,Tampa Bay,Buccaneers,Giants,NaN,NaN,91.0,{'value': 'Partly cloudy'},27.0
125,2009-10-18,1:00PM,1300,12,6,Tampa Bay,Buccaneers,Panthers,NaN,NaN,84.0,{'value': 'Patchy rain possible'},28.0
140,2009-10-25,1:06PM,1300,12,7,Tampa Bay,Buccaneers,Patriots,NaN,NaN,88.0,{'value': 'Partly cloudy'},37.0
162,2009-11-08,1:03PM,1300,12,9,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,91.0,{'value': 'Sunny'},10.0
184,2009-11-22,1:00PM,1300,12,11,Tampa Bay,Buccaneers,Saints,NaN,NaN,80.0,{'value': 'Sunny'},12.0
221,2009-12-13,1:00PM,1300,12,14,Tampa Bay,Buccaneers,Jets,NaN,NaN,86.0,{'value': 'Sunny'},9.0
263,2009-01-03,1:03PM,1300,12,17,Tampa Bay,Buccaneers,Falcons,NaN,NaN,77.0,{'value': 'Partly cloudy'},59.0
279,2010-09-12,1:02PM,1300,12,1,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate rain at times'},67.0
307,2010-09-26,1:03PM,1300,12,3,Tampa Bay,Buccaneers,Steelers,NaN,NaN,92.0,{'value': 'Patchy rain possible'},40.0

In [50]:
#locations_list = ({'Franchise': ['Chicago', 'Green Bay', 'Arizona', 'Baltimore', 'Buffalo', 'Carolina', 'Cincinnati', 'Cleveland', 'Denver', 'Indianapolis', 'Jacksonville', 'Kansas City', 'Miami', 'New England', 'New York', 'Oakland', 'Philadelphia', 'Pittsburgh', 'St. Louis', 'San Diego', 'San Francisco', 'Seattle', 'Tampa Bay', 'Tennessee', 'Washington'], 'Latitude': [41.529998779296875, 44.29999923706055, 33.27000045776367, 39.16999816894531, 42.540000915527344, 35.13999938964844, 39.060001373291016, 41.29999923706055, 39.43000030517578, 39.459999084472656, 30.200000762939453, 39.060001373291016, 25.459999084472656, 42.209999084472656, 40.43000030517578, 37.470001220703125, 39.56999969482422, 40.2599983215332, 38.380001068115234, 32.43000030517578, 37.47999954223633, 47.36000061035156, 27.56999969482422, 36.09000015258789, 38.540000915527344], 'Longitude': [-87.37999725341797, -88.01000213623047, -112.05000305175781, -76.37000274658203, -78.52999877929688, -80.5, -84.30999755859375, -81.41000366210938, -105.01000213623047, -86.08999633789062, -81.4000015258789, -94.37000274658203, -80.12000274658203, -71.04000091552734, -74.01000213623047, -122.12999725341797, -75.06999969482422, -80.0, -90.11000061035156, -118.08999633789062, -122.23999786376953, -122.19999694824219, -82.2699966430664, -86.4800033569336, -77.01000213623047]})
#locations = pd.DataFrame(locations_list)
#locations = locations.round(2)

In [51]:
merged["Latitude"] = merged["Latitude"].fillna(27.57)
merged["Longitude"] = merged["Longitude"].fillna(-82.27)

In [52]:
merged.head(25)

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
5,2008-09-07,1:02PM,1300,12,1,Buffalo,Bills,Bills,42.54,-78.53,82.0,{'value': 'Partly cloudy'},38.0
6,2008-09-07,1:05PM,1300,12,1,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
7,2008-09-07,1:06PM,1300,12,1,Baltimore,Ravens,Ravens,39.17,-76.37,82.0,{'value': 'Partly cloudy'},38.0
8,2008-09-07,4:15PM,1600,15,1,San Diego,Chargers,Panthers,32.43,-118.09,76.0,{'value': 'Partly cloudy'},29.0
9,2008-09-07,4:16PM,1600,15,1,Cleveland,Browns,Cowboys,41.30,-81.41,80.0,{'value': 'Sunny'},0.0
10,2008-09-07,4:16PM,1600,15,1,San Francisco,49ers,Cardinals,37.48,-122.24,61.0,{'value': 'Partly cloudy'},57.0
11,2008-09-07,8:23PM,2000,19,1,Indianapolis,Colts,Bears,39.46,-86.09,77.0,{'value': 'Clear'},16.0
12,2008-09-08,7:10PM,1900,18,1,Green Bay,Packers,Packers,44.30,-88.01,56.0,{'value': 'Light rain shower'},89.0
13,2008-09-08,10:22PM,2200,21,1,Oakland,Raiders,Broncos,37.47,-122.13,57.0,{'value': 'Patchy rain possible'},35.0
14,2008-09-14,1:00PM,1300,12,2,St. Louis,Rams,Giants,38.38,-90.11,94.0,{'value': 'Sunny'},2.0
15,2008-09-14,1:00PM,1300,12,2,Kansas City,Chiefs,Raiders,39.06,-94.37,77.0,{'value': 'Torrential rain shower'},66.0
16,2008-09-14,1:02PM,1300,12,2,Cincinnati,Bengals,Titans,39.06,-84.31,77.0,{'value': 'Torrential rain shower'},66.0
17,2008-09-14,1:03PM,1300,12,2,Washington,Redskins,Redskins,38.54,-77.01,94.0,{'value': 'Sunny'},2.0
18,2008-09-14,1:03PM,1300,12,2,Jacksonville,Jaguars,Bills,30.20,-81.40,64.0,{'value': 'Sunny'},0.0
19,2008-09-14,1:03PM,1300,12,2,Carolina,Panthers,Panthers,35.14,-80.50,80.0,{'value': 'Partly cloudy'},47.0
20,2008-09-14,4:05PM,1600,15,2,Tampa Bay,Buccaneers,Buccaneers,27.57,-82.27,81.0,{'value': 'Moderate or heavy rain shower'},71.0
21,2008-09-14,4:06PM,1600,15,2,Seattle,Seahawks,49ers,47.36,-122.20,66.0,{'value': 'Sunny'},3.0
22,2008-09-14,4:15PM,1600,15,2,Denver,Broncos,Broncos,39.43,-105.01,78.0,{'value': 'Moderate or heavy rain shower'},48.0
23,2008-09-14,4:15PM,1600,15,2,New York,Jets,Patriots,40.43,-74.01,66.0,{'value': 'Sunny'},3.0
24,2008-09-14,4:15PM,1600,15,2,Arizona,Cardinals,Cardinals,33.27,-112.05,66.0,{'value': 'Sunny'},3.0

In [53]:
#empty_locations["Latitude"] = empty_locations["Latitude"].fillna(27.57)
#empty_locations["Longitude"] = empty_locations["Longitude"].fillna(-82.27)

In [54]:
#filled_locations = empty_locations
#filled_locations

In [55]:
# titans and other teams with blank rows/pulls

In [56]:
#empty_pull = merged[merged.weatherDesc.isnull()]
#empty_pull

In [57]:
#empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]] = empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]].fillna(0)
#empty_pull

In [58]:
#empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]] = empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]].astype(int)
#empty_pull.dtypes

In [59]:
#empty_pull["Full Date"] = empty_pull["Full Date"].str.replace('/','-')
#empty_pull["Full Date"] = pd.to_datetime(empty_pull["Full Date"], format="%Y-%m-%d")
#empty_pull

In [60]:
#test = "http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key=6cd0fcd19b014508966202712210906&q=36.09,-86.48&date=2008-09-21&tp=24&format=json"

In [61]:
#base_url = "http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key=6cd0fcd19b014508966202712210906&q=36.09,-86.48&date="
#for index, row in empty_pull.iterrows():
#    try:
#
 #       date = row["Full Date"]
  #      weather_url = f"{base_url},{date}&tp=24&format=json"
   #     weather_info = requests.get(weather_url).json()
    #    
        #print("------------")
        #pprint(weather_info)
        #print("------------")
        
     #   empty_pull.loc[index, "Starting Game Temp (F)"] = weather_info['data']['weather'][0]['hourly'][0]['tempF']
      #  empty_pull.loc[index, "weatherDesc"] = weather_info['data']['weather'][0]['hourly'][0]['weatherDesc']
       # empty_pull.loc[index, "cloudcover"]= weather_info['data']['weather'][0]['hourly'][0]['cloudcover']
        #
        #print("------------")
        #print(weather_info)
        #print("------------")
     #   T.sleep(.5)
     #   print(date)
   # except (KeyError,IndexError):
   #     print("------------")
   #     print("interrupt asap")
   #     print(weather_url)
   #     print(index)
   #     print("------------")
   #     pass

In [62]:
#empty_pull

In [63]:
# run API call last time for the blanks (mainly titans) - it will be for average of day.

In [64]:
#Step 3

In [65]:
#merged_full = pd.concat([merged, filled_locations],keys=["x", "y"], axis=0)

In [66]:
#merged_full = merged_full.sort_index()

In [68]:
merged

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,{'value': 'Partly cloudy'},53.0
463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,{'value': 'Sunny'},3.0
464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,{'value': 'Partly cloudy'},40.0
465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,{'value': 'Overcast'},100.0
466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,{'value': 'Partly cloudy'},57.0

In [69]:
# Step 4 remove duplicates
merged = merged.drop_duplicates()
merged

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,{'value': 'Partly cloudy'},53.0
463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,{'value': 'Sunny'},3.0
464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,{'value': 'Partly cloudy'},40.0
465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,{'value': 'Overcast'},100.0
466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,{'value': 'Partly cloudy'},57.0

In [70]:
merged = merged.reset_index()

In [71]:
merged

,index,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,{'value': 'Partly cloudy'},53.0
1745,463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,{'value': 'Sunny'},3.0
1746,464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,{'value': 'Partly cloudy'},40.0
1747,465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,{'value': 'Overcast'},100.0
1748,466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,{'value': 'Partly cloudy'},57.0

In [72]:
#weather description
merged["weatherDesc"] = merged["weatherDesc"].str.replace("{'value': '","")
merged

<ipython-input-72-406d35f996d7>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  merged["weatherDesc"] = merged["weatherDesc"].str.replace("{'value': '","")

,index,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,Clear'},0.0
1,1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,Partly cloudy'},38.0
2,2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,Light rain shower'},97.0
3,3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,Partly cloudy'},38.0
4,4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,Partly cloudy'},53.0
1745,463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,Sunny'},3.0
1746,464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,Partly cloudy'},40.0
1747,465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,Overcast'},100.0
1748,466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,Partly cloudy'},57.0

In [73]:
#merged_full1 = merged_full

In [75]:
merged["weatherDesc"] = merged["weatherDesc"].str[:-2]

In [77]:
merged

,index,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,Clear,0.0
1,1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,Partly cloudy,38.0
2,2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,Light rain shower,97.0
3,3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,Partly cloudy,38.0
4,4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,Sunny,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,Partly cloudy,53.0
1745,463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,Sunny,3.0
1746,464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,Partly cloudy,40.0
1747,465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,Overcast,100.0
1748,466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,Partly cloudy,57.0

In [78]:
merged["cloudcover"] = [str(x)+'%' for x in merged["cloudcover"]]
merged

,index,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,Clear,0.0%
1,1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,Partly cloudy,38.0%
2,2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,Light rain shower,97.0%
3,3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,Partly cloudy,38.0%
4,4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,Sunny,14.0%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,Partly cloudy,53.0%
1745,463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,Sunny,3.0%
1746,464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,Partly cloudy,40.0%
1747,465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,Overcast,100.0%
1748,466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,Partly cloudy,57.0%

In [79]:
merged.rename(columns={"Starting Game Temp (F)":"Kickoff Temp",
                            "weatherDesc":"Weather Element",
                            "cloudcover":"Cloudiness",
                           "Time":"Kickoff Time"}, inplace=True)

In [80]:
merged.head()

,index,Full Date,Kickoff Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Kickoff Temp,Weather Element,Cloudiness
0,0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,Clear,0.0%
1,1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,Partly cloudy,38.0%
2,2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,Light rain shower,97.0%
3,3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,Partly cloudy,38.0%
4,4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,Sunny,14.0%

In [81]:
merged["Season"] = merged["Full Date"].str[0:4]
merged["Month"] = merged["Full Date"].str[6:7]

In [82]:
merged

,index,Full Date,Kickoff Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Kickoff Temp,Weather Element,Cloudiness,Season,Month
0,0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,Clear,0.0%,2008,9
1,1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,Partly cloudy,38.0%,2008,9
2,2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,Light rain shower,97.0%,2008,9
3,3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,Partly cloudy,38.0%,2008,9
4,4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,Sunny,14.0%,2008,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,Partly cloudy,53.0%,2015,1
1745,463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,Sunny,3.0%,2015,1
1746,464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,Partly cloudy,40.0%,2015,1
1747,465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,Overcast,100.0%,2015,1
1748,466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,Partly cloudy,57.0%,2015,2

In [103]:
dropped_df = merged[
    ["Season","Month","Week","Kickoff Time",
     "Winner","Home Team","City","Kickoff Temp",
     "Weather Element","Cloudiness"]]

In [104]:
dropped_df = dropped_df.sort_index()

In [105]:
dropped_df["Stadium Location"] ="(" + merged["Latitude"].astype(str) + ", " + merged["Longitude"].astype(str) + ")"

In [106]:
dropped_df

,Season,Month,Week,Kickoff Time,Winner,Home Team,City,Kickoff Temp,Weather Element,Cloudiness,Stadium Location
0,2008,9,1,7:08PM,Giants,Giants,New York,72.0,Clear,0.0%,"(40.43, -74.01)"
1,2008,9,1,1:02PM,Eagles,Eagles,Philadelphia,82.0,Partly cloudy,38.0%,"(39.57, -75.07)"
2,2008,9,1,1:02PM,Jets,Dolphins,Miami,59.0,Light rain shower,97.0%,"(25.46, -80.12)"
3,2008,9,1,1:02PM,Patriots,Patriots,New England,82.0,Partly cloudy,38.0%,"(42.21, -71.04)"
4,2008,9,1,1:02PM,Steelers,Steelers,Pittsburgh,72.0,Sunny,14.0%,"(40.26, -80.0)"
...,...,...,...,...,...,...,...,...,...,...,...
1744,2015,1,Division,1:06PM,Panthers,Panthers,Carolina,34.0,Partly cloudy,53.0%,"(35.14, -80.5)"
1745,2015,1,Division,4:40PM,Broncos,Broncos,Denver,56.0,Sunny,3.0%,"(39.43, -105.01)"
1746,2015,1,ConfChamp,3:05PM,Broncos,Broncos,Denver,64.0,Partly cloudy,40.0%,"(39.43, -105.01)"
1747,2015,1,ConfChamp,6:42PM,Panthers,Panthers,Carolina,33.0,Overcast,100.0%,"(35.14, -80.5)"
1748,2015,2,SuperBowl,6:39PM,Broncos,Broncos,Denver,58.0,Partly cloudy,57.0%,"(39.43, -105.01)"

In [86]:
locations_list = ({'Franchise': ['Chicago', 'Green Bay', 'Arizona', 'Baltimore', 'Buffalo', 'Carolina', 'Cincinnati', 'Cleveland', 'Denver', 'Indianapolis', 'Jacksonville', 'Kansas City', 'Miami', 'New England', 'New York', 'Oakland', 'Philadelphia', 'Pittsburgh', 'St. Louis', 'San Diego', 'San Francisco', 'Seattle', 'Tampa Bay', 'Tennessee', 'Washington'], 'Latitude': [41.529998779296875, 44.29999923706055, 33.27000045776367, 39.16999816894531, 42.540000915527344, 35.13999938964844, 39.060001373291016, 41.29999923706055, 39.43000030517578, 39.459999084472656, 30.200000762939453, 39.060001373291016, 25.459999084472656, 42.209999084472656, 40.43000030517578, 37.470001220703125, 39.56999969482422, 40.2599983215332, 38.380001068115234, 32.43000030517578, 37.47999954223633, 47.36000061035156, 27.56999969482422, 36.09000015258789, 38.540000915527344], 'Longitude': [-87.37999725341797, -88.01000213623047, -112.05000305175781, -76.37000274658203, -78.52999877929688, -80.5, -84.30999755859375, -81.41000366210938, -105.01000213623047, -86.08999633789062, -81.4000015258789, -94.37000274658203, -80.12000274658203, -71.04000091552734, -74.01000213623047, -122.12999725341797, -75.06999969482422, -80.0, -90.11000061035156, -118.08999633789062, -122.23999786376953, -122.19999694824219, -82.2699966430664, -86.4800033569336, -77.01000213623047]})
locations = pd.DataFrame(locations_list)
locations = locations.round(2)

In [87]:
locations

        Franchise  Latitude  Longitude
0         Chicago     41.53     -87.38
1       Green Bay     44.30     -88.01
2         Arizona     33.27    -112.05
3       Baltimore     39.17     -76.37
4         Buffalo     42.54     -78.53
5        Carolina     35.14     -80.50
6      Cincinnati     39.06     -84.31
7       Cleveland     41.30     -81.41
8          Denver     39.43    -105.01
9    Indianapolis     39.46     -86.09
10   Jacksonville     30.20     -81.40
11    Kansas City     39.06     -94.37
12          Miami     25.46     -80.12
13    New England     42.21     -71.04
14       New York     40.43     -74.01
15        Oakland     37.47    -122.13
16   Philadelphia     39.57     -75.07
17     Pittsburgh     40.26     -80.00
18      St. Louis     38.38     -90.11
19      San Diego     32.43    -118.09
20  San Francisco     37.48    -122.24
21        Seattle     47.36    -122.20
22      Tampa Bay     27.57     -82.27
23      Tennessee     36.09     -86.48
24     Washington     38.54     -77.01

In [108]:
url = 'https://simple.wikipedia.org/wiki/List_of_National_Football_League_stadiums'

In [110]:
scrape = pd.read_html(url)
type(scrape)

list

In [111]:
stadium = scrape[1]
stadium

,Image,Stadium,Capacity,City,State/Province,Surface,Home teams,Opened,Refs
0,NaN,MetLife Stadium,82500,East Rutherford,New Jersey,UBU Sports Speed Series S5-M Synthetic Turf,New York GiantsNew York Jets,2010,[2]
1,NaN,FedEx Field,82000,Landover,Maryland,419 Tifway Bermuda Grass,Washington Redskins,1997,[3]
2,NaN,Lambeau Field,81435,Green Bay,Wisconsin,Desso GrassMaster,Green Bay Packers,1957,[4]
3,NaN,AT&T Stadium,80000,Arlington,Texas,Hellas Matrix Turf (artificial)[5],Dallas Cowboys,2009,[6]
4,NaN,Arrowhead Stadium,76416,Kansas City,Missouri,Bermuda grass,Kansas City Chiefs,1972,[7]
5,NaN,Empower Field at Mile High,76125,Denver,Colorado,Kentucky bluegrass,Denver Broncos,2001,[8]
6,NaN,Bank of America Stadium,72220,Charlotte,North Carolina,Bermuda grass,Carolina Panthers,1996,[9]
7,NaN,Mercedes-Benz Superdome,73208,New Orleans,Louisiana,FieldTurf Revolution 360,New Orleans Saints,1975,[10]
8,NaN,NRG Stadium,72220,Houston,Texas,Hellas Matrix Turf (artificial),Houston Texans,2002,[11]
9,NaN,New Era Field,71068,Orchard Park,New York,A-Turf Titan 50,Buffalo Bills,1973,[12][13]
10,NaN,M&T Bank Stadium,71008,Baltimore,Maryland,Bermuda grass,Baltimore Ravens,1998,[14]
11,NaN,Mercedes-Benz Stadium,71000,Atlanta,Georgia,FieldTurf Revolution,Atlanta Falcons,2017,[15]
12,NaN,SoFi Stadium,70240,Inglewood,California,Hellas Matrix Turf (artificial),Los Angeles ChargersLos Angeles Rams,2020,NaN
13,[[File:|center|100x75px|]],Lincoln Financial Field,69596,Philadelphia,Pennsylvania,Desso GrassMaster,Philadelphia Eagles,2003,[16]
14,NaN,Nissan Stadium,69143,Nashville,Tennessee,Bermuda grass,Tennessee Titans,1999,[17]
15,[[File:|center|100x75px|]],TIAA Bank Field,69132,Jacksonville,Florida,Bermuda grass,Jacksonville Jaguars,1995,[18]
16,NaN,Lumen Field,69000,Seattle,Washington,FieldTurf Revolution 360,Seattle Seahawks,2002,[19]
17,NaN,Levi's Stadium,68500,Santa Clara,California,Kentucky bluegrass/perennial ryegrass mixture,San Francisco 49ers,2014,[20]
18,NaN,Heinz Field,68400,Pittsburgh,Pennsylvania,Kentucky bluegrass,Pittsburgh Steelers,2001,[21]
19,NaN,FirstEnergy Stadium,67895,Cleveland,Ohio,Kentucky bluegrass,Cleveland Browns,1999,[22]
20,NaN,Lucas Oil Stadium,67000,Indianapolis,Indiana,Shaw Sports Momentum Pro,Indianapolis Colts,2008,[23]
21,NaN,Gillette Stadium,66829,Foxborough,Massachusetts,FieldTurf CORE,New England Patriots,2002,[24]
22,NaN,U.S. Bank Stadium,66655,Minneapolis,Minnesota,UBU Sports Speed Series S5-M,Minnesota Vikings,2016,NaN
23,NaN,Raymond James Stadium,65890,Tampa,Florida,Bermuda grass,Tampa Bay Buccaneers,1998,[25]
24,NaN,Paul Brown Stadium,65790,Cincinnati,Ohio,UBU Speed Series S5-M,Cincinnati Bengals,2000,[26]
25,NaN,Hard Rock Stadium,65326,Miami Gardens,Florida,Platinum TE Paspalum,Miami Dolphins,1987,[27]
26,NaN,Allegiant Stadium,65000,Paradise,Nevada,Bermuda Grass[a],Las Vegas Raiders,2020,NaN
27,NaN,Ford Field,65000,Detroit,Michigan,FieldTurf Classic HD,Detroit Lions,2002,[28]
28,NaN,State Farm Stadium,63400,Glendale,Arizona,Bermuda grass,Arizona Cardinals,2006,[29]
29,NaN,Soldier Field,61500,Chicago,Illinois,Kentucky bluegrass,Chicago Bears,1924,[30]