In [1]:
#filled_locations = empty_locations
#filled_locations

In [2]:
#empty_locations["Latitude"] = empty_locations["Latitude"].fillna(27.57)
#empty_locations["Longitude"] = empty_locations["Longitude"].fillna(-82.27)

In [3]:
import pandas as pd
import requests
from pprint import pprint
import time as T
from datetime import datetime

In [4]:
#table_1 = pd.read_csv("Table 1.csv")
#table_2 = pd.read_csv("Table 2.csv")
#table_3 = pd.read_csv("Table 3.csv")
#table_4 = pd.read_csv("Table 4.csv")
#table_5 = pd.read_csv("Table 5.csv")
#table_6 = pd.read_csv("Table 6.csv")

In [5]:
table_1 = pd.read_csv("Table 1.csv", parse_dates = [0])
table_2 = pd.read_csv("Table 2.csv", parse_dates = [0])
table_3 = pd.read_csv("Table 3.csv", parse_dates = [0])
table_4 = pd.read_csv("Table 4.csv", parse_dates = [0])
table_5 = pd.read_csv("Table 5.csv", parse_dates = [0])
table_6 = pd.read_csv("Table 6.csv", parse_dates = [0])

In [6]:
table_1['Full Date'] = table_1['Full Date'].dt.strftime('%Y-%m-%d')
table_2['Full Date'] = table_2['Full Date'].dt.strftime('%Y-%m-%d')
table_3['Full Date'] = table_3['Full Date'].dt.strftime('%Y-%m-%d')
table_4['Full Date'] = table_4['Full Date'].dt.strftime('%Y-%m-%d')
table_5['Full Date'] = table_5['Full Date'].dt.strftime('%Y-%m-%d')
table_6['Full Date'] = table_6['Full Date'].dt.strftime('%Y-%m-%d')

In [7]:
#table_1.head()

In [8]:
merged = pd.concat([table_1,table_2,table_3,table_4,table_5,table_6], axis=0)

In [9]:
# Step one: fill in blanks for Tampa Bay

In [10]:
empty_locations = merged[merged.Latitude.isnull()]
empty_locations

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
20,2008-09-14,4:05PM,1600,15,2,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate or heavy rain shower'},71.0
44,2008-09-28,1:02PM,1300,12,4,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,90.0,{'value': 'Patchy rain possible'},46.0
62,2008-10-12,1:02PM,1300,12,6,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,84.0,{'value': 'Moderate or heavy rain shower'},37.0
2,2008-10-19,8:23PM,2000,19,7,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,74.0,{'value': 'Light rain shower'},62.0
42,2008-11-16,1:02PM,1300,12,11,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,86.0,{'value': 'Overcast'},90.0
67,2008-11-30,1:02PM,1300,12,13,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,76.0,{'value': 'Sunny'},0.0
33,2008-12-21,1:02PM,1300,12,16,Tampa Bay,Buccaneers,Chargers,NaN,NaN,84.0,{'value': 'Sunny'},10.0
45,2008-12-28,1:02PM,1300,12,17,Tampa Bay,Buccaneers,Raiders,NaN,NaN,85.0,{'value': 'Sunny'},15.0
68,2009-09-13,1:03PM,1300,12,1,Tampa Bay,Buccaneers,Cowboys,NaN,NaN,86.0,{'value': 'Cloudy'},75.0
90,2009-09-27,1:00PM,1300,12,3,Tampa Bay,Buccaneers,Giants,NaN,NaN,91.0,{'value': 'Partly cloudy'},27.0
125,2009-10-18,1:00PM,1300,12,6,Tampa Bay,Buccaneers,Panthers,NaN,NaN,84.0,{'value': 'Patchy rain possible'},28.0
140,2009-10-25,1:06PM,1300,12,7,Tampa Bay,Buccaneers,Patriots,NaN,NaN,88.0,{'value': 'Partly cloudy'},37.0
162,2009-11-08,1:03PM,1300,12,9,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,91.0,{'value': 'Sunny'},10.0
184,2009-11-22,1:00PM,1300,12,11,Tampa Bay,Buccaneers,Saints,NaN,NaN,80.0,{'value': 'Sunny'},12.0
221,2009-12-13,1:00PM,1300,12,14,Tampa Bay,Buccaneers,Jets,NaN,NaN,86.0,{'value': 'Sunny'},9.0
263,2009-01-03,1:03PM,1300,12,17,Tampa Bay,Buccaneers,Falcons,NaN,NaN,77.0,{'value': 'Partly cloudy'},59.0
279,2010-09-12,1:02PM,1300,12,1,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate rain at times'},67.0
307,2010-09-26,1:03PM,1300,12,3,Tampa Bay,Buccaneers,Steelers,NaN,NaN,92.0,{'value': 'Patchy rain possible'},40.0

In [11]:
#locations_list = ({'Franchise': ['Chicago', 'Green Bay', 'Arizona', 'Baltimore', 'Buffalo', 'Carolina', 'Cincinnati', 'Cleveland', 'Denver', 'Indianapolis', 'Jacksonville', 'Kansas City', 'Miami', 'New England', 'New York', 'Oakland', 'Philadelphia', 'Pittsburgh', 'St. Louis', 'San Diego', 'San Francisco', 'Seattle', 'Tampa Bay', 'Tennessee', 'Washington'], 'Latitude': [41.529998779296875, 44.29999923706055, 33.27000045776367, 39.16999816894531, 42.540000915527344, 35.13999938964844, 39.060001373291016, 41.29999923706055, 39.43000030517578, 39.459999084472656, 30.200000762939453, 39.060001373291016, 25.459999084472656, 42.209999084472656, 40.43000030517578, 37.470001220703125, 39.56999969482422, 40.2599983215332, 38.380001068115234, 32.43000030517578, 37.47999954223633, 47.36000061035156, 27.56999969482422, 36.09000015258789, 38.540000915527344], 'Longitude': [-87.37999725341797, -88.01000213623047, -112.05000305175781, -76.37000274658203, -78.52999877929688, -80.5, -84.30999755859375, -81.41000366210938, -105.01000213623047, -86.08999633789062, -81.4000015258789, -94.37000274658203, -80.12000274658203, -71.04000091552734, -74.01000213623047, -122.12999725341797, -75.06999969482422, -80.0, -90.11000061035156, -118.08999633789062, -122.23999786376953, -122.19999694824219, -82.2699966430664, -86.4800033569336, -77.01000213623047]})
#locations = pd.DataFrame(locations_list)
#locations = locations.round(2)

In [12]:
merged["Latitude"] = merged["Latitude"].fillna(27.57)
merged["Longitude"] = merged["Longitude"].fillna(-82.27)

In [13]:
#merged.head(25)

In [14]:
# titans and other teams with blank rows/pulls

In [15]:
#empty_pull = merged[merged.weatherDesc.isnull()]
#empty_pull

In [16]:
#empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]] = empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]].fillna(0)
#empty_pull

In [17]:
#empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]] = empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]].astype(int)
#empty_pull.dtypes

In [18]:
#empty_pull["Full Date"] = empty_pull["Full Date"].str.replace('/','-')
#empty_pull["Full Date"] = pd.to_datetime(empty_pull["Full Date"], format="%Y-%m-%d")
#empty_pull

In [19]:
#test = "http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key=6cd0fcd19b014508966202712210906&q=36.09,-86.48&date=2008-09-21&tp=24&format=json"

In [20]:
#base_url = "http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key=6cd0fcd19b014508966202712210906&q=36.09,-86.48&date="
#for index, row in empty_pull.iterrows():
#    try:
#
 #       date = row["Full Date"]
  #      weather_url = f"{base_url},{date}&tp=24&format=json"
   #     weather_info = requests.get(weather_url).json()
    #    
        #print("------------")
        #pprint(weather_info)
        #print("------------")
        
     #   empty_pull.loc[index, "Starting Game Temp (F)"] = weather_info['data']['weather'][0]['hourly'][0]['tempF']
      #  empty_pull.loc[index, "weatherDesc"] = weather_info['data']['weather'][0]['hourly'][0]['weatherDesc']
       # empty_pull.loc[index, "cloudcover"]= weather_info['data']['weather'][0]['hourly'][0]['cloudcover']
        #
        #print("------------")
        #print(weather_info)
        #print("------------")
     #   T.sleep(.5)
     #   print(date)
   # except (KeyError,IndexError):
   #     print("------------")
   #     print("interrupt asap")
   #     print(weather_url)
   #     print(index)
   #     print("------------")
   #     pass

In [21]:
#empty_pull

In [22]:
# run API call last time for the blanks (mainly titans) - it will be for average of day.

In [23]:
#Step 3

In [24]:
#merged_full = pd.concat([merged, filled_locations],keys=["x", "y"], axis=0)

In [25]:
#merged_full = merged_full.sort_index()

In [26]:
merged

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,{'value': 'Partly cloudy'},53.0
463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,{'value': 'Sunny'},3.0
464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,{'value': 'Partly cloudy'},40.0
465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,{'value': 'Overcast'},100.0
466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,{'value': 'Partly cloudy'},57.0

In [27]:
# Step 4 remove duplicates
merged = merged.drop_duplicates()
merged

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,{'value': 'Partly cloudy'},53.0
463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,{'value': 'Sunny'},3.0
464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,{'value': 'Partly cloudy'},40.0
465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,{'value': 'Overcast'},100.0
466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,{'value': 'Partly cloudy'},57.0

In [28]:
merged = merged.reset_index()

In [29]:
merged

,index,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,{'value': 'Partly cloudy'},53.0
1745,463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,{'value': 'Sunny'},3.0
1746,464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,{'value': 'Partly cloudy'},40.0
1747,465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,{'value': 'Overcast'},100.0
1748,466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,{'value': 'Partly cloudy'},57.0

In [30]:
#weather description
merged["weatherDesc"] = merged["weatherDesc"].str.replace("{'value': '","")
merged

<ipython-input-30-406d35f996d7>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  merged["weatherDesc"] = merged["weatherDesc"].str.replace("{'value': '","")

,index,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,Clear'},0.0
1,1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,Partly cloudy'},38.0
2,2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,Light rain shower'},97.0
3,3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,Partly cloudy'},38.0
4,4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,Partly cloudy'},53.0
1745,463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,Sunny'},3.0
1746,464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,Partly cloudy'},40.0
1747,465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,Overcast'},100.0
1748,466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,Partly cloudy'},57.0

In [31]:
#merged_full1 = merged_full

In [32]:
merged["weatherDesc"] = merged["weatherDesc"].str[:-2]

In [33]:
merged

,index,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,Clear,0.0
1,1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,Partly cloudy,38.0
2,2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,Light rain shower,97.0
3,3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,Partly cloudy,38.0
4,4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,Sunny,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,Partly cloudy,53.0
1745,463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,Sunny,3.0
1746,464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,Partly cloudy,40.0
1747,465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,Overcast,100.0
1748,466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,Partly cloudy,57.0

In [34]:
merged["cloudcover"] = [str(x)+'%' for x in merged["cloudcover"]]
merged

,index,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,Clear,0.0%
1,1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,Partly cloudy,38.0%
2,2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,Light rain shower,97.0%
3,3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,Partly cloudy,38.0%
4,4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,Sunny,14.0%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,Partly cloudy,53.0%
1745,463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,Sunny,3.0%
1746,464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,Partly cloudy,40.0%
1747,465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,Overcast,100.0%
1748,466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,Partly cloudy,57.0%

In [35]:
merged.rename(columns={"Starting Game Temp (F)":"Kickoff Temp (F)",
                            "weatherDesc":"Weather Element",
                            "cloudcover":"Cloudiness",
                           "Time":"Kickoff Time"}, inplace=True)

In [36]:
merged.head()

,index,Full Date,Kickoff Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Kickoff Temp (F),Weather Element,Cloudiness
0,0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,Clear,0.0%
1,1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,Partly cloudy,38.0%
2,2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,Light rain shower,97.0%
3,3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,Partly cloudy,38.0%
4,4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,Sunny,14.0%

In [37]:
merged["Season"] = merged["Full Date"].str[0:4]
merged["Month"] = merged["Full Date"].str[6:7]

In [38]:
merged

,index,Full Date,Kickoff Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Kickoff Temp (F),Weather Element,Cloudiness,Season,Month
0,0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,Clear,0.0%,2008,9
1,1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,Partly cloudy,38.0%,2008,9
2,2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,Light rain shower,97.0%,2008,9
3,3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,Partly cloudy,38.0%,2008,9
4,4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,Sunny,14.0%,2008,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,Partly cloudy,53.0%,2015,1
1745,463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,Sunny,3.0%,2015,1
1746,464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,Partly cloudy,40.0%,2015,1
1747,465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,Overcast,100.0%,2015,1
1748,466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,Partly cloudy,57.0%,2015,2

In [40]:
dropped_df = merged[
    ["Season","Month","Week","Kickoff Time",
     "Winner","Home Team","City","Kickoff Temp (F)",
     "Weather Element","Cloudiness"]]

In [41]:
dropped_df = dropped_df.sort_index()

In [42]:
dropped_df["Stadium Location"] ="(" + merged["Latitude"].astype(str) + ", " + merged["Longitude"].astype(str) + ")"

In [43]:
new_df = dropped_df
new_df

,Season,Month,Week,Kickoff Time,Winner,Home Team,City,Kickoff Temp (F),Weather Element,Cloudiness,Stadium Location
0,2008,9,1,7:08PM,Giants,Giants,New York,72.0,Clear,0.0%,"(40.43, -74.01)"
1,2008,9,1,1:02PM,Eagles,Eagles,Philadelphia,82.0,Partly cloudy,38.0%,"(39.57, -75.07)"
2,2008,9,1,1:02PM,Jets,Dolphins,Miami,59.0,Light rain shower,97.0%,"(25.46, -80.12)"
3,2008,9,1,1:02PM,Patriots,Patriots,New England,82.0,Partly cloudy,38.0%,"(42.21, -71.04)"
4,2008,9,1,1:02PM,Steelers,Steelers,Pittsburgh,72.0,Sunny,14.0%,"(40.26, -80.0)"
...,...,...,...,...,...,...,...,...,...,...,...
1744,2015,1,Division,1:06PM,Panthers,Panthers,Carolina,34.0,Partly cloudy,53.0%,"(35.14, -80.5)"
1745,2015,1,Division,4:40PM,Broncos,Broncos,Denver,56.0,Sunny,3.0%,"(39.43, -105.01)"
1746,2015,1,ConfChamp,3:05PM,Broncos,Broncos,Denver,64.0,Partly cloudy,40.0%,"(39.43, -105.01)"
1747,2015,1,ConfChamp,6:42PM,Panthers,Panthers,Carolina,33.0,Overcast,100.0%,"(35.14, -80.5)"
1748,2015,2,SuperBowl,6:39PM,Broncos,Broncos,Denver,58.0,Partly cloudy,57.0%,"(39.43, -105.01)"

In [44]:
# copy locations dictionary from other notebook
# locations_list = ({'Franchise': ['Chicago', 'Green Bay', 'Arizona', 'Baltimore', 'Buffalo', 'Carolina', 'Cincinnati', 'Cleveland', 'Denver', 'Indianapolis', 'Jacksonville', 'Kansas City', 'Miami', 'New England', 'New York', 'Oakland', 'Philadelphia', 'Pittsburgh', 'St. Louis', 'San Diego', 'San Francisco', 'Seattle', 'Tampa Bay', 'Tennessee', 'Washington'], 'Latitude': [41.529998779296875, 44.29999923706055, 33.27000045776367, 39.16999816894531, 42.540000915527344, 35.13999938964844, 39.060001373291016, 41.29999923706055, 39.43000030517578, 39.459999084472656, 30.200000762939453, 39.060001373291016, 25.459999084472656, 42.209999084472656, 40.43000030517578, 37.470001220703125, 39.56999969482422, 40.2599983215332, 38.380001068115234, 32.43000030517578, 37.47999954223633, 47.36000061035156, 27.56999969482422, 36.09000015258789, 38.540000915527344], 'Longitude': [-87.37999725341797, -88.01000213623047, -112.05000305175781, -76.37000274658203, -78.52999877929688, -80.5, -84.30999755859375, -81.41000366210938, -105.01000213623047, -86.08999633789062, -81.4000015258789, -94.37000274658203, -80.12000274658203, -71.04000091552734, -74.01000213623047, -122.12999725341797, -75.06999969482422, -80.0, -90.11000061035156, -118.08999633789062, -122.23999786376953, -122.19999694824219, -82.2699966430664, -86.4800033569336, -77.01000213623047]})

In [45]:
city= ['Chicago', 'Green Bay', 'Arizona', 'Baltimore', 'Buffalo', 
      'Carolina', 'Cincinnati','Cleveland', 'Denver', 
      'Indianapolis', 'Jacksonville', 'Kansas City',
      'Miami', 'New England', 'New York', 'Oakland', 'Philadelphia',
      'Pittsburgh', 'St. Louis', 'San Diego', 'San Francisco', 
      'Seattle', 'Tampa Bay', 'Tennessee', 'Washington']

In [46]:
# Stadium df
url = 'https://simple.wikipedia.org/wiki/List_of_National_Football_League_stadiums'
scrape = pd.read_html(url)
#type(scrape)
#scrape
stadium_scrape = scrape[1]

In [47]:
stadium_name = stadium_scrape[["Stadium","City","Home teams"]]
stadium_name

,Stadium,City,Home teams
0,MetLife Stadium,East Rutherford,New York GiantsNew York Jets
1,FedEx Field,Landover,Washington Redskins
2,Lambeau Field,Green Bay,Green Bay Packers
3,AT&T Stadium,Arlington,Dallas Cowboys
4,Arrowhead Stadium,Kansas City,Kansas City Chiefs
5,Empower Field at Mile High,Denver,Denver Broncos
6,Bank of America Stadium,Charlotte,Carolina Panthers
7,Mercedes-Benz Superdome,New Orleans,New Orleans Saints
8,NRG Stadium,Houston,Houston Texans
9,New Era Field,Orchard Park,Buffalo Bills
10,M&T Bank Stadium,Baltimore,Baltimore Ravens
11,Mercedes-Benz Stadium,Atlanta,Atlanta Falcons
12,SoFi Stadium,Inglewood,Los Angeles ChargersLos Angeles Rams
13,Lincoln Financial Field,Philadelphia,Philadelphia Eagles
14,Nissan Stadium,Nashville,Tennessee Titans
15,TIAA Bank Field,Jacksonville,Jacksonville Jaguars
16,Lumen Field,Seattle,Seattle Seahawks
17,Levi's Stadium,Santa Clara,San Francisco 49ers
18,Heinz Field,Pittsburgh,Pittsburgh Steelers
19,FirstEnergy Stadium,Cleveland,Cleveland Browns
20,Lucas Oil Stadium,Indianapolis,Indianapolis Colts
21,Gillette Stadium,Foxborough,New England Patriots
22,U.S. Bank Stadium,Minneapolis,Minnesota Vikings
23,Raymond James Stadium,Tampa,Tampa Bay Buccaneers
24,Paul Brown Stadium,Cincinnati,Cincinnati Bengals
25,Hard Rock Stadium,Miami Gardens,Miami Dolphins
26,Allegiant Stadium,Paradise,Las Vegas Raiders
27,Ford Field,Detroit,Detroit Lions
28,State Farm Stadium,Glendale,Arizona Cardinals
29,Soldier Field,Chicago,Chicago Bears

In [48]:
stadium_list = ['Soldier Field','Lambeau Field','State Farm Stadium','M&T Bank Stadium','New Era Field',
           'Bank of America Stadium','Paul Brown Stadium','FirstEnergy Stadium','Empower Field at Mile High',
           'Lucas Oil Stadium','TIAA Bank Field','Arrowhead Stadium',
          'Hard Rock Stadium','Gillette Stadium','MetLife Stadium','Oakland Coliseum(*)','Lincoln Financial Field',
          'Heinz Field','Edward Jones Dome','Qualcomm Stadium','Levis Stadium',
          'Lumen Field','Raymond James Stadium','Nissan Stadium','FedEx Field']

In [49]:
stadium_dict = {'City':city,
                'Stadium':stadium_list
               }
stadium_dict
stadium_df = pd.DataFrame(stadium_dict)
stadium_df

             City                     Stadium
0         Chicago               Soldier Field
1       Green Bay               Lambeau Field
2         Arizona          State Farm Stadium
3       Baltimore            M&T Bank Stadium
4         Buffalo               New Era Field
5        Carolina     Bank of America Stadium
6      Cincinnati          Paul Brown Stadium
7       Cleveland         FirstEnergy Stadium
8          Denver  Empower Field at Mile High
9    Indianapolis           Lucas Oil Stadium
10   Jacksonville             TIAA Bank Field
11    Kansas City           Arrowhead Stadium
12          Miami           Hard Rock Stadium
13    New England            Gillette Stadium
14       New York             MetLife Stadium
15        Oakland         Oakland Coliseum(*)
16   Philadelphia     Lincoln Financial Field
17     Pittsburgh                 Heinz Field
18      St. Louis           Edward Jones Dome
19      San Diego            Qualcomm Stadium
20  San Francisco               Levis Stadium
21        Seattle                 Lumen Field
22      Tampa Bay       Raymond James Stadium
23      Tennessee              Nissan Stadium
24     Washington                 FedEx Field

In [50]:
merged_stadium = pd.merge(left=new_df, right=stadium_df, how='left', left_on="City", right_on="City")

In [51]:
merged_stadium

,Season,Month,Week,Kickoff Time,Winner,Home Team,City,Kickoff Temp (F),Weather Element,Cloudiness,Stadium Location,Stadium
0,2008,9,1,7:08PM,Giants,Giants,New York,72.0,Clear,0.0%,"(40.43, -74.01)",MetLife Stadium
1,2008,9,1,1:02PM,Eagles,Eagles,Philadelphia,82.0,Partly cloudy,38.0%,"(39.57, -75.07)",Lincoln Financial Field
2,2008,9,1,1:02PM,Jets,Dolphins,Miami,59.0,Light rain shower,97.0%,"(25.46, -80.12)",Hard Rock Stadium
3,2008,9,1,1:02PM,Patriots,Patriots,New England,82.0,Partly cloudy,38.0%,"(42.21, -71.04)",Gillette Stadium
4,2008,9,1,1:02PM,Steelers,Steelers,Pittsburgh,72.0,Sunny,14.0%,"(40.26, -80.0)",Heinz Field
...,...,...,...,...,...,...,...,...,...,...,...,...
1744,2015,1,Division,1:06PM,Panthers,Panthers,Carolina,34.0,Partly cloudy,53.0%,"(35.14, -80.5)",Bank of America Stadium
1745,2015,1,Division,4:40PM,Broncos,Broncos,Denver,56.0,Sunny,3.0%,"(39.43, -105.01)",Empower Field at Mile High
1746,2015,1,ConfChamp,3:05PM,Broncos,Broncos,Denver,64.0,Partly cloudy,40.0%,"(39.43, -105.01)",Empower Field at Mile High
1747,2015,1,ConfChamp,6:42PM,Panthers,Panthers,Carolina,33.0,Overcast,100.0%,"(35.14, -80.5)",Bank of America Stadium
1748,2015,2,SuperBowl,6:39PM,Broncos,Broncos,Denver,58.0,Partly cloudy,57.0%,"(39.43, -105.01)",Empower Field at Mile High

KeyError: 'Kickoff Temp'