In [13]:
import pandas as pd
import requests
from pprint import pprint
import time as T
from datetime import datetime

In [14]:
#table_1 = pd.read_csv("Table 1.csv")
#table_2 = pd.read_csv("Table 2.csv")
#table_3 = pd.read_csv("Table 3.csv")
#table_4 = pd.read_csv("Table 4.csv")
#table_5 = pd.read_csv("Table 5.csv")
#table_6 = pd.read_csv("Table 6.csv")

In [15]:
table_1 = pd.read_csv("Table 1.csv", parse_dates = [0])
table_2 = pd.read_csv("Table 2.csv", parse_dates = [0])
table_3 = pd.read_csv("Table 3.csv", parse_dates = [0])
table_4 = pd.read_csv("Table 4.csv", parse_dates = [0])
table_5 = pd.read_csv("Table 5.csv", parse_dates = [0])
table_6 = pd.read_csv("Table 6.csv", parse_dates = [0])

In [16]:
table_1['Full Date'] = table_1['Full Date'].dt.strftime('%Y-%m-%d')
table_2['Full Date'] = table_2['Full Date'].dt.strftime('%Y-%m-%d')
table_3['Full Date'] = table_3['Full Date'].dt.strftime('%Y-%m-%d')
table_4['Full Date'] = table_4['Full Date'].dt.strftime('%Y-%m-%d')
table_5['Full Date'] = table_5['Full Date'].dt.strftime('%Y-%m-%d')
table_6['Full Date'] = table_6['Full Date'].dt.strftime('%Y-%m-%d')

In [17]:
#table_1.head()

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0

In [18]:
merged = pd.concat([table_1,table_2,table_3,table_4,table_5,table_6], axis=0)
merged.head(100)

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,2008-11-02,1:02PM,1300,12,9,Chicago,Bears,Bears,41.53,-87.38,89.0,{'value': 'Sunny'},6.0
16,2008-11-02,1:02PM,1300,12,9,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
17,2008-11-02,1:02PM,1300,12,9,Cleveland,Browns,Ravens,41.30,-81.41,89.0,{'value': 'Sunny'},6.0
18,2008-11-02,1:02PM,1300,12,9,Buffalo,Bills,Jets,42.54,-78.53,81.0,{'value': 'Cloudy'},71.0
19,2008-11-02,1:02PM,1300,12,9,Cincinnati,Bengals,Bengals,39.06,-84.31,81.0,{'value': 'Cloudy'},71.0

In [19]:
# Step one: fill in blanks for Tampa Bay

In [20]:
empty_locations = merged[merged.Latitude.isnull()]
empty_locations

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
20,2008-09-14,4:05PM,1600,15,2,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate or heavy rain shower'},71.0
44,2008-09-28,1:02PM,1300,12,4,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,90.0,{'value': 'Patchy rain possible'},46.0
62,2008-10-12,1:02PM,1300,12,6,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,84.0,{'value': 'Moderate or heavy rain shower'},37.0
2,2008-10-19,8:23PM,2000,19,7,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,74.0,{'value': 'Light rain shower'},62.0
42,2008-11-16,1:02PM,1300,12,11,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,86.0,{'value': 'Overcast'},90.0
67,2008-11-30,1:02PM,1300,12,13,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,76.0,{'value': 'Sunny'},0.0
33,2008-12-21,1:02PM,1300,12,16,Tampa Bay,Buccaneers,Chargers,NaN,NaN,84.0,{'value': 'Sunny'},10.0
45,2008-12-28,1:02PM,1300,12,17,Tampa Bay,Buccaneers,Raiders,NaN,NaN,85.0,{'value': 'Sunny'},15.0
68,2009-09-13,1:03PM,1300,12,1,Tampa Bay,Buccaneers,Cowboys,NaN,NaN,86.0,{'value': 'Cloudy'},75.0
90,2009-09-27,1:00PM,1300,12,3,Tampa Bay,Buccaneers,Giants,NaN,NaN,91.0,{'value': 'Partly cloudy'},27.0
125,2009-10-18,1:00PM,1300,12,6,Tampa Bay,Buccaneers,Panthers,NaN,NaN,84.0,{'value': 'Patchy rain possible'},28.0
140,2009-10-25,1:06PM,1300,12,7,Tampa Bay,Buccaneers,Patriots,NaN,NaN,88.0,{'value': 'Partly cloudy'},37.0
162,2009-11-08,1:03PM,1300,12,9,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,91.0,{'value': 'Sunny'},10.0
184,2009-11-22,1:00PM,1300,12,11,Tampa Bay,Buccaneers,Saints,NaN,NaN,80.0,{'value': 'Sunny'},12.0
221,2009-12-13,1:00PM,1300,12,14,Tampa Bay,Buccaneers,Jets,NaN,NaN,86.0,{'value': 'Sunny'},9.0
263,2009-01-03,1:03PM,1300,12,17,Tampa Bay,Buccaneers,Falcons,NaN,NaN,77.0,{'value': 'Partly cloudy'},59.0
279,2010-09-12,1:02PM,1300,12,1,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate rain at times'},67.0
307,2010-09-26,1:03PM,1300,12,3,Tampa Bay,Buccaneers,Steelers,NaN,NaN,92.0,{'value': 'Patchy rain possible'},40.0

In [21]:
#locations_list = ({'Franchise': ['Chicago', 'Green Bay', 'Arizona', 'Baltimore', 'Buffalo', 'Carolina', 'Cincinnati', 'Cleveland', 'Denver', 'Indianapolis', 'Jacksonville', 'Kansas City', 'Miami', 'New England', 'New York', 'Oakland', 'Philadelphia', 'Pittsburgh', 'St. Louis', 'San Diego', 'San Francisco', 'Seattle', 'Tampa Bay', 'Tennessee', 'Washington'], 'Latitude': [41.529998779296875, 44.29999923706055, 33.27000045776367, 39.16999816894531, 42.540000915527344, 35.13999938964844, 39.060001373291016, 41.29999923706055, 39.43000030517578, 39.459999084472656, 30.200000762939453, 39.060001373291016, 25.459999084472656, 42.209999084472656, 40.43000030517578, 37.470001220703125, 39.56999969482422, 40.2599983215332, 38.380001068115234, 32.43000030517578, 37.47999954223633, 47.36000061035156, 27.56999969482422, 36.09000015258789, 38.540000915527344], 'Longitude': [-87.37999725341797, -88.01000213623047, -112.05000305175781, -76.37000274658203, -78.52999877929688, -80.5, -84.30999755859375, -81.41000366210938, -105.01000213623047, -86.08999633789062, -81.4000015258789, -94.37000274658203, -80.12000274658203, -71.04000091552734, -74.01000213623047, -122.12999725341797, -75.06999969482422, -80.0, -90.11000061035156, -118.08999633789062, -122.23999786376953, -122.19999694824219, -82.2699966430664, -86.4800033569336, -77.01000213623047]})
#locations = pd.DataFrame(locations_list)
#locations = locations.round(2)

In [22]:
empty_locations["Latitude"] = empty_locations["Latitude"].fillna(27.57)
empty_locations["Longitude"] = empty_locations["Longitude"].fillna(-82.27)

<ipython-input-22-7371f5293bef>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_locations["Latitude"] = empty_locations["Latitude"].fillna(27.57)
<ipython-input-22-7371f5293bef>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_locations["Longitude"] = empty_locations["Longitude"].fillna(-82.27)

In [23]:
filled_locations = empty_locations
filled_locations

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
20,2008-09-14,4:05PM,1600,15,2,Tampa Bay,Buccaneers,Buccaneers,27.57,-82.27,81.0,{'value': 'Moderate or heavy rain shower'},71.0
44,2008-09-28,1:02PM,1300,12,4,Tampa Bay,Buccaneers,Buccaneers,27.57,-82.27,90.0,{'value': 'Patchy rain possible'},46.0
62,2008-10-12,1:02PM,1300,12,6,Tampa Bay,Buccaneers,Buccaneers,27.57,-82.27,84.0,{'value': 'Moderate or heavy rain shower'},37.0
2,2008-10-19,8:23PM,2000,19,7,Tampa Bay,Buccaneers,Buccaneers,27.57,-82.27,74.0,{'value': 'Light rain shower'},62.0
42,2008-11-16,1:02PM,1300,12,11,Tampa Bay,Buccaneers,Buccaneers,27.57,-82.27,86.0,{'value': 'Overcast'},90.0
67,2008-11-30,1:02PM,1300,12,13,Tampa Bay,Buccaneers,Buccaneers,27.57,-82.27,76.0,{'value': 'Sunny'},0.0
33,2008-12-21,1:02PM,1300,12,16,Tampa Bay,Buccaneers,Chargers,27.57,-82.27,84.0,{'value': 'Sunny'},10.0
45,2008-12-28,1:02PM,1300,12,17,Tampa Bay,Buccaneers,Raiders,27.57,-82.27,85.0,{'value': 'Sunny'},15.0
68,2009-09-13,1:03PM,1300,12,1,Tampa Bay,Buccaneers,Cowboys,27.57,-82.27,86.0,{'value': 'Cloudy'},75.0
90,2009-09-27,1:00PM,1300,12,3,Tampa Bay,Buccaneers,Giants,27.57,-82.27,91.0,{'value': 'Partly cloudy'},27.0
125,2009-10-18,1:00PM,1300,12,6,Tampa Bay,Buccaneers,Panthers,27.57,-82.27,84.0,{'value': 'Patchy rain possible'},28.0
140,2009-10-25,1:06PM,1300,12,7,Tampa Bay,Buccaneers,Patriots,27.57,-82.27,88.0,{'value': 'Partly cloudy'},37.0
162,2009-11-08,1:03PM,1300,12,9,Tampa Bay,Buccaneers,Buccaneers,27.57,-82.27,91.0,{'value': 'Sunny'},10.0
184,2009-11-22,1:00PM,1300,12,11,Tampa Bay,Buccaneers,Saints,27.57,-82.27,80.0,{'value': 'Sunny'},12.0
221,2009-12-13,1:00PM,1300,12,14,Tampa Bay,Buccaneers,Jets,27.57,-82.27,86.0,{'value': 'Sunny'},9.0
263,2009-01-03,1:03PM,1300,12,17,Tampa Bay,Buccaneers,Falcons,27.57,-82.27,77.0,{'value': 'Partly cloudy'},59.0
279,2010-09-12,1:02PM,1300,12,1,Tampa Bay,Buccaneers,Buccaneers,27.57,-82.27,81.0,{'value': 'Moderate rain at times'},67.0
307,2010-09-26,1:03PM,1300,12,3,Tampa Bay,Buccaneers,Steelers,27.57,-82.27,92.0,{'value': 'Patchy rain possible'},40.0

In [24]:
# titans and other teams with blank rows/pulls

In [25]:
empty_pull = merged[merged.weatherDesc.isnull()]
empty_pull

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
6,2008-09-07,1:05PM,1300,12,1,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
26,2008-09-21,1:02PM,1300,12,3,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
45,2008-09-28,1:03PM,1300,12,4,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
13,2008-10-27,8:39PM,2000,19,8,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
16,2008-11-02,1:02PM,1300,12,9,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,2015-10-25,1:02PM,1300,12,7,Tennessee,Titans,Falcons,36.09,-86.48,NaN,NaN,NaN
358,2015-11-15,1:03PM,1300,12,10,Tennessee,Titans,Panthers,36.09,-86.48,NaN,NaN,NaN
382,2015-11-29,1:02PM,1300,12,12,Tennessee,Titans,Raiders,36.09,-86.48,NaN,NaN,NaN
393,2015-12-06,1:02PM,1300,12,13,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
435,2015-12-27,1:02PM,1300,12,16,Tennessee,Titans,Texans,36.09,-86.48,NaN,NaN,NaN

In [26]:
empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]] = empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]].fillna(0)
empty_pull

/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
6,2008-09-07,1:05PM,1300,12,1,Tennessee,Titans,Titans,36.09,-86.48,0.0,0,0.0
26,2008-09-21,1:02PM,1300,12,3,Tennessee,Titans,Titans,36.09,-86.48,0.0,0,0.0
45,2008-09-28,1:03PM,1300,12,4,Tennessee,Titans,Titans,36.09,-86.48,0.0,0,0.0
13,2008-10-27,8:39PM,2000,19,8,Tennessee,Titans,Titans,36.09,-86.48,0.0,0,0.0
16,2008-11-02,1:02PM,1300,12,9,Tennessee,Titans,Titans,36.09,-86.48,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,2015-10-25,1:02PM,1300,12,7,Tennessee,Titans,Falcons,36.09,-86.48,0.0,0,0.0
358,2015-11-15,1:03PM,1300,12,10,Tennessee,Titans,Panthers,36.09,-86.48,0.0,0,0.0
382,2015-11-29,1:02PM,1300,12,12,Tennessee,Titans,Raiders,36.09,-86.48,0.0,0,0.0
393,2015-12-06,1:02PM,1300,12,13,Tennessee,Titans,Titans,36.09,-86.48,0.0,0,0.0
435,2015-12-27,1:02PM,1300,12,16,Tennessee,Titans,Texans,36.09,-86.48,0.0,0,0.0

In [27]:
empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]] = empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]].astype(int)
empty_pull.dtypes

/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

Full Date                  object
Time                       object
time_conv                   int64
time_index                  int64
Week                       object
City                       object
Home Team                  object
Winner                     object
Latitude                  float64
Longitude                 float64
Starting Game Temp (F)      int64
weatherDesc                 int64
cloudcover                  int64
dtype: object

In [31]:
#empty_pull["Full Date"] = empty_pull["Full Date"].str.replace('/','-')
#empty_pull["Full Date"] = pd.to_datetime(empty_pull["Full Date"], format="%Y-%m-%d")
empty_pull

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
6,2008-09-07,1:05PM,1300,12,1,Tennessee,Titans,Titans,36.09,-86.48,85,{'value': 'Sunny'},6
26,2008-09-21,1:02PM,1300,12,3,Tennessee,Titans,Titans,36.09,-86.48,85,{'value': 'Partly cloudy'},16
45,2008-09-28,1:03PM,1300,12,4,Tennessee,Titans,Titans,36.09,-86.48,82,{'value': 'Mist'},6
13,2008-10-27,8:39PM,2000,19,8,Tennessee,Titans,Titans,36.09,-86.48,49,0,0
16,2008-11-02,1:02PM,1300,12,9,Tennessee,Titans,Titans,36.09,-86.48,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,2015-10-25,1:02PM,1300,12,7,Tennessee,Titans,Falcons,36.09,-86.48,0,0,0
358,2015-11-15,1:03PM,1300,12,10,Tennessee,Titans,Panthers,36.09,-86.48,0,0,0
382,2015-11-29,1:02PM,1300,12,12,Tennessee,Titans,Raiders,36.09,-86.48,0,0,0
393,2015-12-06,1:02PM,1300,12,13,Tennessee,Titans,Titans,36.09,-86.48,0,0,0
435,2015-12-27,1:02PM,1300,12,16,Tennessee,Titans,Texans,36.09,-86.48,0,0,0

In [29]:
#test = "http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key=6cd0fcd19b014508966202712210906&q=36.09,-86.48&date=2008-09-21&tp=24&format=json"

In [30]:
base_url = "http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key=6cd0fcd19b014508966202712210906&q=36.09,-86.48&date="
for index, row in empty_pull.iterrows():
    try:

        date = row["Full Date"]
        weather_url = f"{base_url},{date}&tp=24&format=json"
        weather_info = requests.get(weather_url).json()
        
        #print("------------")
        #pprint(weather_info)
        #print("------------")
        
        empty_pull.loc[index, "Starting Game Temp (F)"] = weather_info['data']['weather'][0]['hourly'][0]['tempF']
        empty_pull.loc[index, "weatherDesc"] = weather_info['data']['weather'][0]['hourly'][0]['weatherDesc']
        empty_pull.loc[index, "cloudcover"]= weather_info['data']['weather'][0]['hourly'][0]['cloudcover']
        
        #print("------------")
        #print(weather_info)
        #print("------------")
        T.sleep(.5)
        print(date)
    except (KeyError,IndexError):
        print("------------")
        print("interrupt asap")
        print(weather_url)
        print(index)
        print("------------")
        pass

/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1700: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, v, pi)
/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

2008-09-07

/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1700: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, v, pi)
/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

2008-09-21

/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1700: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, v, pi)
/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

2008-09-28

/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

ValueError: Must have equal len keys and value when setting with an iterable

In [ ]:
empty_pull

In [ ]:
# run API call last time for the blanks (mainly titans) - it will be for average of day.

In [ ]:
#Step 3

In [32]:
merged_full = pd.concat([merged, filled_locations], axis=0)

In [33]:
merged_full

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,2009-11-22,1:00PM,1300,12,11,Tampa Bay,Buccaneers,Saints,27.57,-82.27,80.0,{'value': 'Sunny'},12.0
221,2009-12-13,1:00PM,1300,12,14,Tampa Bay,Buccaneers,Jets,27.57,-82.27,86.0,{'value': 'Sunny'},9.0
263,2009-01-03,1:03PM,1300,12,17,Tampa Bay,Buccaneers,Falcons,27.57,-82.27,77.0,{'value': 'Partly cloudy'},59.0
279,2010-09-12,1:02PM,1300,12,1,Tampa Bay,Buccaneers,Buccaneers,27.57,-82.27,81.0,{'value': 'Moderate rain at times'},67.0
307,2010-09-26,1:03PM,1300,12,3,Tampa Bay,Buccaneers,Steelers,27.57,-82.27,92.0,{'value': 'Patchy rain possible'},40.0

In [34]:
# Step 4 remove duplicates
merged_full = merged_full.drop_duplicates()
merged_full

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,2009-11-22,1:00PM,1300,12,11,Tampa Bay,Buccaneers,Saints,27.57,-82.27,80.0,{'value': 'Sunny'},12.0
221,2009-12-13,1:00PM,1300,12,14,Tampa Bay,Buccaneers,Jets,27.57,-82.27,86.0,{'value': 'Sunny'},9.0
263,2009-01-03,1:03PM,1300,12,17,Tampa Bay,Buccaneers,Falcons,27.57,-82.27,77.0,{'value': 'Partly cloudy'},59.0
279,2010-09-12,1:02PM,1300,12,1,Tampa Bay,Buccaneers,Buccaneers,27.57,-82.27,81.0,{'value': 'Moderate rain at times'},67.0
307,2010-09-26,1:03PM,1300,12,3,Tampa Bay,Buccaneers,Steelers,27.57,-82.27,92.0,{'value': 'Patchy rain possible'},40.0

In [36]:
# clean table 

#weather description
merged_full["weatherDesc"] = merged_full["weatherDesc"].str.replace("{'value': '","")
merged_full["weatherDesc"] = merged_full["weatherDesc"].str.replace("'}'","")

merged_full = merged_full.rename["Starting Game Temp (F)"]

<ipython-input-36-861c787e9aaf>:4: FutureWarning: The default value of regex will change from True to False in a future version.
  merged_full["weatherDesc"] = merged_full["weatherDesc"].str.replace("{'value': '","")
<ipython-input-36-861c787e9aaf>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_full["weatherDesc"] = merged_full["weatherDesc"].str.replace("{'value': '","")

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,2009-11-22,1:00PM,1300,12,11,Tampa Bay,Buccaneers,Saints,27.57,-82.27,80.0,Sunny'},12.0
221,2009-12-13,1:00PM,1300,12,14,Tampa Bay,Buccaneers,Jets,27.57,-82.27,86.0,Sunny'},9.0
263,2009-01-03,1:03PM,1300,12,17,Tampa Bay,Buccaneers,Falcons,27.57,-82.27,77.0,Partly cloudy'},59.0
279,2010-09-12,1:02PM,1300,12,1,Tampa Bay,Buccaneers,Buccaneers,27.57,-82.27,81.0,Moderate rain at times'},67.0
307,2010-09-26,1:03PM,1300,12,3,Tampa Bay,Buccaneers,Steelers,27.57,-82.27,92.0,Patchy rain possible'},40.0