In [2]:
import pandas as pd

In [4]:
table_1 = pd.read_csv("Table 1.csv")
table_2 = pd.read_csv("Table 2.csv")
table_3 = pd.read_csv("Table 3.csv")

In [6]:
table_1

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2008-10-19,1:02PM,1300,12,7,New York,Giants,Giants,40.43,-74.01,68.0,{'value': 'Sunny'},0.0
76,2008-10-19,1:02PM,1300,12,7,Chicago,Bears,Bears,41.53,-87.38,86.0,{'value': 'Sunny'},5.0
77,2008-10-19,1:04PM,1300,12,7,Cincinnati,Bengals,Steelers,39.06,-84.31,81.0,{'value': 'Sunny'},15.0
78,2008-10-19,1:04PM,1300,12,7,Carolina,Panthers,Panthers,35.14,-80.50,55.0,{'value': 'Sunny'},9.0
79,2008-10-19,4:15PM,1600,15,7,Oakland,Raiders,Raiders,37.47,-122.13,56.0,{'value': 'Overcast'},100.0

In [8]:
merged = pd.concat([table_1,table_2,table_3], axis=0)
merged

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,2010-10-10,4:05PM,1600,15,5,Arizona,Cardinals,Cardinals,33.27,-112.05,68.0,{'value': 'Light rain shower'},53.0
336,2010-10-10,4:15PM,1600,15,5,Oakland,Raiders,Raiders,37.47,-122.13,59.0,{'value': 'Partly cloudy'},25.0
337,2010-10-10,8:30PM,2000,19,5,San Francisco,49ers,Eagles,37.48,-122.24,55.0,{'value': 'Clear'},10.0
338,2010-10-11,9:15PM,2100,20,5,New York,Jets,Jets,40.43,-74.01,56.0,{'value': 'Partly cloudy'},31.0
339,2010-10-17,1:00PM,1300,12,6,St. Louis,Rams,Rams,38.38,-90.11,71.0,{'value': 'Sunny'},3.0

In [25]:
empty_locations = merged[merged.Latitude.isnull()]
empty_locations

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
20,2008-09-14,4:05PM,1600,15,2,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate or heavy rain shower'},71.0
44,2008-09-28,1:02PM,1300,12,4,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,90.0,{'value': 'Patchy rain possible'},46.0
62,2008-10-12,1:02PM,1300,12,6,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,84.0,{'value': 'Moderate or heavy rain shower'},37.0
2,2008-10-19,8:23PM,2000,19,7,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,74.0,{'value': 'Light rain shower'},62.0
42,2008-11-16,1:02PM,1300,12,11,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,86.0,{'value': 'Overcast'},90.0
67,2008-11-30,1:02PM,1300,12,13,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,76.0,{'value': 'Sunny'},0.0
108,2008-12-21,1:02PM,1300,12,16,Tampa Bay,Buccaneers,Chargers,NaN,NaN,NaN,NaN,NaN
120,2008-12-28,1:02PM,1300,12,17,Tampa Bay,Buccaneers,Raiders,NaN,NaN,NaN,NaN,NaN
143,2009-09-13,1:03PM,1300,12,1,Tampa Bay,Buccaneers,Cowboys,NaN,NaN,NaN,NaN,NaN
165,2009-09-27,1:00PM,1300,12,3,Tampa Bay,Buccaneers,Giants,NaN,NaN,NaN,NaN,NaN
200,2009-10-18,1:00PM,1300,12,6,Tampa Bay,Buccaneers,Panthers,NaN,NaN,NaN,NaN,NaN
215,2009-10-25,1:06PM,1300,12,7,Tampa Bay,Buccaneers,Patriots,NaN,NaN,NaN,NaN,NaN
237,2009-11-08,1:03PM,1300,12,9,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,NaN,NaN,NaN
259,2009-11-22,1:00PM,1300,12,11,Tampa Bay,Buccaneers,Saints,NaN,NaN,NaN,NaN,NaN
296,2009-12-13,1:00PM,1300,12,14,Tampa Bay,Buccaneers,Jets,NaN,NaN,NaN,NaN,NaN
338,2009-01-03,1:03PM,1300,12,17,Tampa Bay,Buccaneers,Falcons,NaN,NaN,NaN,NaN,NaN
354,2010-09-12,1:02PM,1300,12,1,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,NaN,NaN,NaN
382,2010-09-26,1:03PM,1300,12,3,Tampa Bay,Buccaneers,Steelers,NaN,NaN,NaN,NaN,NaN
33,2008-12-21,1:02PM,1300,12,16,Tampa Bay,Buccaneers,Chargers,NaN,NaN,84.0,{'value': 'Sunny'},10.0
45,2008-12-28,1:02PM,1300,12,17,Tampa Bay,Buccaneers,Raiders,NaN,NaN,85.0,{'value': 'Sunny'},15.0
68,2009-09-13,1:03PM,1300,12,1,Tampa Bay,Buccaneers,Cowboys,NaN,NaN,86.0,{'value': 'Cloudy'},75.0
90,2009-09-27,1:00PM,1300,12,3,Tampa Bay,Buccaneers,Giants,NaN,NaN,91.0,{'value': 'Partly cloudy'},27.0
125,2009-10-18,1:00PM,1300,12,6,Tampa Bay,Buccaneers,Panthers,NaN,NaN,84.0,{'value': 'Patchy rain possible'},28.0
140,2009-10-25,1:06PM,1300,12,7,Tampa Bay,Buccaneers,Patriots,NaN,NaN,88.0,{'value': 'Partly cloudy'},37.0
162,2009-11-08,1:03PM,1300,12,9,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,91.0,{'value': 'Sunny'},10.0
184,2009-11-22,1:00PM,1300,12,11,Tampa Bay,Buccaneers,Saints,NaN,NaN,80.0,{'value': 'Sunny'},12.0
221,2009-12-13,1:00PM,1300,12,14,Tampa Bay,Buccaneers,Jets,NaN,NaN,86.0,{'value': 'Sunny'},9.0
263,2009-01-03,1:03PM,1300,12,17,Tampa Bay,Buccaneers,Falcons,NaN,NaN,77.0,{'value': 'Partly cloudy'},59.0
279,2010-09-12,1:02PM,1300,12,1,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate rain at times'},67.0
307,2010-09-26,1:03PM,1300,12,3,Tampa Bay,Buccaneers,Steelers,NaN,NaN,92.0,{'value': 'Patchy rain possible'},40.0

In [17]:
empty_pull = merged[merged.weatherDesc.isnull()]
empty_pull

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
6,2008-09-07,1:05PM,1300,12,1,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
26,2008-09-21,1:02PM,1300,12,3,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
45,2008-09-28,1:03PM,1300,12,4,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
13,2008-10-27,8:39PM,2000,19,8,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
16,2008-11-02,1:02PM,1300,12,9,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,2009-12-20,1:02PM,1300,12,15,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
245,2009-12-25,7:34PM,1900,18,16,Tennessee,Titans,Chargers,36.09,-86.48,NaN,NaN,NaN
282,2010-09-12,1:02PM,1300,12,1,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
293,2010-09-19,1:02PM,1300,12,2,Tennessee,Titans,Steelers,36.09,-86.48,NaN,NaN,NaN
318,2010-10-03,1:02PM,1300,12,4,Tennessee,Titans,Broncos,36.09,-86.48,NaN,NaN,NaN

In [24]:
base_url = "http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key=9b6272a2d2e34f45bab144757210906&q="
for index, row in empty_pull.iterrows():
    try:
        lat = row['Latitude']
        lng = row["Longitude"]
        date = row["Full Date"]
        location = f"{lat},{lng}"
        weather_test = f"{base_url},{location}&date={date}&tp=24&format=json"
        weather_info = requests.get(weather_test).json()
        empty_pull.loc[index, "Starting Game Temp (F)"] = weather_info['data']['weather'][0]['hourly'][time]['tempF']
        empty_pull.loc[index, "weatherDesc"] = weather_info['data']['weather'][0]['hourly'][time]['weatherDesc']
        empty_pull.loc[index, "cloudcover"]= weather_info['data']['weather'][0]['hourly'][time]['cloudcover']

Tennessee        34
New York         28
Pittsburgh       19
Arizona          18
San Diego        15
Indianapolis     15
Carolina         15
New England      14
Chicago          14
St. Louis        14
Oakland          13
Philadelphia     13
Miami            13
Buffalo          13
Baltimore        13
Jacksonville     13
Green Bay        13
Cincinnati       13
San Francisco    12
Kansas City      12
Tampa Bay        12
Washington       12
Denver           12
Cleveland        12
Seattle          12
Name: City, dtype: int64