In [2]:
import pandas as pd

In [4]:
table_1 = pd.read_csv("Table 1.csv")
table_2 = pd.read_csv("Table 2.csv")
table_3 = pd.read_csv("Table 3.csv")

In [6]:
table_1

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2008-10-19,1:02PM,1300,12,7,New York,Giants,Giants,40.43,-74.01,68.0,{'value': 'Sunny'},0.0
76,2008-10-19,1:02PM,1300,12,7,Chicago,Bears,Bears,41.53,-87.38,86.0,{'value': 'Sunny'},5.0
77,2008-10-19,1:04PM,1300,12,7,Cincinnati,Bengals,Steelers,39.06,-84.31,81.0,{'value': 'Sunny'},15.0
78,2008-10-19,1:04PM,1300,12,7,Carolina,Panthers,Panthers,35.14,-80.50,55.0,{'value': 'Sunny'},9.0
79,2008-10-19,4:15PM,1600,15,7,Oakland,Raiders,Raiders,37.47,-122.13,56.0,{'value': 'Overcast'},100.0

In [8]:
merged = pd.concat([table_1,table_2,table_3], axis=0)
merged

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,2010-10-10,4:05PM,1600,15,5,Arizona,Cardinals,Cardinals,33.27,-112.05,68.0,{'value': 'Light rain shower'},53.0
336,2010-10-10,4:15PM,1600,15,5,Oakland,Raiders,Raiders,37.47,-122.13,59.0,{'value': 'Partly cloudy'},25.0
337,2010-10-10,8:30PM,2000,19,5,San Francisco,49ers,Eagles,37.48,-122.24,55.0,{'value': 'Clear'},10.0
338,2010-10-11,9:15PM,2100,20,5,New York,Jets,Jets,40.43,-74.01,56.0,{'value': 'Partly cloudy'},31.0
339,2010-10-17,1:00PM,1300,12,6,St. Louis,Rams,Rams,38.38,-90.11,71.0,{'value': 'Sunny'},3.0