In [1]:
import pandas as pd

In [19]:
table_1 = pd.read_csv("Table 1.csv")
table_2 = pd.read_csv("Table 2.csv")
table_3 = pd.read_csv("Table 3.csv")
table_4 = pd.read_csv("Table 4.csv")
table_5 = pd.read_csv("Table 5.csv")
table_6 = pd.read_csv("Table 6.csv")

In [20]:
merged = pd.concat([table_1,table_2,table_3,table_4,table_5,table_6], axis=0)
merged

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,{'value': 'Partly cloudy'},53.0
463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,{'value': 'Sunny'},3.0
464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,{'value': 'Partly cloudy'},40.0
465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,{'value': 'Overcast'},100.0
466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,{'value': 'Partly cloudy'},57.0

In [21]:
empty_locations = merged[merged.Latitude.isnull()]
empty_locations

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
20,2008-09-14,4:05PM,1600,15,2,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate or heavy rain shower'},71.0
44,2008-09-28,1:02PM,1300,12,4,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,90.0,{'value': 'Patchy rain possible'},46.0
62,2008-10-12,1:02PM,1300,12,6,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,84.0,{'value': 'Moderate or heavy rain shower'},37.0
2,10/19/08,8:23PM,2000,19,7,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,74.0,{'value': 'Light rain shower'},62.0
42,11/16/08,1:02PM,1300,12,11,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,86.0,{'value': 'Overcast'},90.0
67,11/30/08,1:02PM,1300,12,13,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,76.0,{'value': 'Sunny'},0.0
33,2008-12-21,1:02PM,1300,12,16,Tampa Bay,Buccaneers,Chargers,NaN,NaN,84.0,{'value': 'Sunny'},10.0
45,2008-12-28,1:02PM,1300,12,17,Tampa Bay,Buccaneers,Raiders,NaN,NaN,85.0,{'value': 'Sunny'},15.0
68,2009-09-13,1:03PM,1300,12,1,Tampa Bay,Buccaneers,Cowboys,NaN,NaN,86.0,{'value': 'Cloudy'},75.0
90,2009-09-27,1:00PM,1300,12,3,Tampa Bay,Buccaneers,Giants,NaN,NaN,91.0,{'value': 'Partly cloudy'},27.0
125,2009-10-18,1:00PM,1300,12,6,Tampa Bay,Buccaneers,Panthers,NaN,NaN,84.0,{'value': 'Patchy rain possible'},28.0
140,2009-10-25,1:06PM,1300,12,7,Tampa Bay,Buccaneers,Patriots,NaN,NaN,88.0,{'value': 'Partly cloudy'},37.0
162,2009-11-08,1:03PM,1300,12,9,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,91.0,{'value': 'Sunny'},10.0
184,2009-11-22,1:00PM,1300,12,11,Tampa Bay,Buccaneers,Saints,NaN,NaN,80.0,{'value': 'Sunny'},12.0
221,2009-12-13,1:00PM,1300,12,14,Tampa Bay,Buccaneers,Jets,NaN,NaN,86.0,{'value': 'Sunny'},9.0
263,2009-01-03,1:03PM,1300,12,17,Tampa Bay,Buccaneers,Falcons,NaN,NaN,77.0,{'value': 'Partly cloudy'},59.0
279,2010-09-12,1:02PM,1300,12,1,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate rain at times'},67.0
307,2010-09-26,1:03PM,1300,12,3,Tampa Bay,Buccaneers,Steelers,NaN,NaN,92.0,{'value': 'Patchy rain possible'},40.0

In [25]:
locations_list = ({'Franchise': ['Chicago', 'Green Bay', 'Arizona', 'Baltimore', 'Buffalo', 'Carolina', 'Cincinnati', 'Cleveland', 'Denver', 'Indianapolis', 'Jacksonville', 'Kansas City', 'Miami', 'New England', 'New York', 'Oakland', 'Philadelphia', 'Pittsburgh', 'St. Louis', 'San Diego', 'San Francisco', 'Seattle', 'Tampa Bay', 'Tennessee', 'Washington'], 'Latitude': [41.529998779296875, 44.29999923706055, 33.27000045776367, 39.16999816894531, 42.540000915527344, 35.13999938964844, 39.060001373291016, 41.29999923706055, 39.43000030517578, 39.459999084472656, 30.200000762939453, 39.060001373291016, 25.459999084472656, 42.209999084472656, 40.43000030517578, 37.470001220703125, 39.56999969482422, 40.2599983215332, 38.380001068115234, 32.43000030517578, 37.47999954223633, 47.36000061035156, 27.56999969482422, 36.09000015258789, 38.540000915527344], 'Longitude': [-87.37999725341797, -88.01000213623047, -112.05000305175781, -76.37000274658203, -78.52999877929688, -80.5, -84.30999755859375, -81.41000366210938, -105.01000213623047, -86.08999633789062, -81.4000015258789, -94.37000274658203, -80.12000274658203, -71.04000091552734, -74.01000213623047, -122.12999725341797, -75.06999969482422, -80.0, -90.11000061035156, -118.08999633789062, -122.23999786376953, -122.19999694824219, -82.2699966430664, -86.4800033569336, -77.01000213623047]})
locations = pd.DataFrame(locations_list)
locations = locations.round(2)

In [26]:
filled_locations = pd.merge(left=empty_locations, right=locations, how="inner", left_on="City", right_on="Franchise")
filled_locations

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude_x,Longitude_x,Starting Game Temp (F),weatherDesc,cloudcover,Franchise,Latitude_y,Longitude_y
0,2008-09-14,4:05PM,1600,15,2,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate or heavy rain shower'},71.0,Tampa Bay,27.57,-82.27
1,2008-09-28,1:02PM,1300,12,4,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,90.0,{'value': 'Patchy rain possible'},46.0,Tampa Bay,27.57,-82.27
2,2008-10-12,1:02PM,1300,12,6,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,84.0,{'value': 'Moderate or heavy rain shower'},37.0,Tampa Bay,27.57,-82.27
3,10/19/08,8:23PM,2000,19,7,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,74.0,{'value': 'Light rain shower'},62.0,Tampa Bay,27.57,-82.27
4,11/16/08,1:02PM,1300,12,11,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,86.0,{'value': 'Overcast'},90.0,Tampa Bay,27.57,-82.27
5,11/30/08,1:02PM,1300,12,13,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,76.0,{'value': 'Sunny'},0.0,Tampa Bay,27.57,-82.27
6,2008-12-21,1:02PM,1300,12,16,Tampa Bay,Buccaneers,Chargers,NaN,NaN,84.0,{'value': 'Sunny'},10.0,Tampa Bay,27.57,-82.27
7,2008-12-28,1:02PM,1300,12,17,Tampa Bay,Buccaneers,Raiders,NaN,NaN,85.0,{'value': 'Sunny'},15.0,Tampa Bay,27.57,-82.27
8,2009-09-13,1:03PM,1300,12,1,Tampa Bay,Buccaneers,Cowboys,NaN,NaN,86.0,{'value': 'Cloudy'},75.0,Tampa Bay,27.57,-82.27
9,2009-09-27,1:00PM,1300,12,3,Tampa Bay,Buccaneers,Giants,NaN,NaN,91.0,{'value': 'Partly cloudy'},27.0,Tampa Bay,27.57,-82.27
10,2009-10-18,1:00PM,1300,12,6,Tampa Bay,Buccaneers,Panthers,NaN,NaN,84.0,{'value': 'Patchy rain possible'},28.0,Tampa Bay,27.57,-82.27
11,2009-10-25,1:06PM,1300,12,7,Tampa Bay,Buccaneers,Patriots,NaN,NaN,88.0,{'value': 'Partly cloudy'},37.0,Tampa Bay,27.57,-82.27
12,2009-11-08,1:03PM,1300,12,9,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,91.0,{'value': 'Sunny'},10.0,Tampa Bay,27.57,-82.27
13,2009-11-22,1:00PM,1300,12,11,Tampa Bay,Buccaneers,Saints,NaN,NaN,80.0,{'value': 'Sunny'},12.0,Tampa Bay,27.57,-82.27
14,2009-12-13,1:00PM,1300,12,14,Tampa Bay,Buccaneers,Jets,NaN,NaN,86.0,{'value': 'Sunny'},9.0,Tampa Bay,27.57,-82.27
15,2009-01-03,1:03PM,1300,12,17,Tampa Bay,Buccaneers,Falcons,NaN,NaN,77.0,{'value': 'Partly cloudy'},59.0,Tampa Bay,27.57,-82.27
16,2010-09-12,1:02PM,1300,12,1,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate rain at times'},67.0,Tampa Bay,27.57,-82.27
17,2010-09-26,1:03PM,1300,12,3,Tampa Bay,Buccaneers,Steelers,NaN,NaN,92.0,{'value': 'Patchy rain possible'},40.0,Tampa Bay,27.57,-82.27

In [9]:
empty_pull = merged[merged.weatherDesc.isnull()]
empty_pull

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
6,2008-09-07,1:05PM,1300,12,1,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
26,2008-09-21,1:02PM,1300,12,3,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
45,2008-09-28,1:03PM,1300,12,4,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
13,10/27/08,8:39PM,2000,19,8,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
16,11/2/08,1:02PM,1300,12,9,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,2015-10-25,1:02PM,1300,12,7,Tennessee,Titans,Falcons,36.09,-86.48,NaN,NaN,NaN
358,2015-11-15,1:03PM,1300,12,10,Tennessee,Titans,Panthers,36.09,-86.48,NaN,NaN,NaN
382,2015-11-29,1:02PM,1300,12,12,Tennessee,Titans,Raiders,36.09,-86.48,NaN,NaN,NaN
393,2015-12-06,1:02PM,1300,12,13,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
435,2015-12-27,1:02PM,1300,12,16,Tennessee,Titans,Texans,36.09,-86.48,NaN,NaN,NaN

In [ ]:
base_url = "http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key=9b6272a2d2e34f45bab144757210906&q="
for index, row in empty_pull.iterrows():
    try:
        lat = row['Latitude']
        lng = row["Longitude"]
        date = row["Full Date"]
        location = f"{lat},{lng}"
        weather_test = f"{base_url},{location}&date={date}&tp=24&format=json"
        weather_info = requests.get(weather_test).json()
        empty_pull.loc[index, "Starting Game Temp (F)"] = weather_info['data']['weather'][0]['hourly'][time]['tempF']
        empty_pull.loc[index, "weatherDesc"] = weather_info['data']['weather'][0]['hourly'][time]['weatherDesc']
        empty_pull.loc[index, "cloudcover"]= weather_info['data']['weather'][0]['hourly'][time]['cloudcover']

In [5]:
merged = merged.drop_duplicates()
merged

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,2015-01-17,1:06PM,1300,12,Division,Carolina,Panthers,Panthers,35.14,-80.50,34.0,{'value': 'Partly cloudy'},53.0
463,2015-01-17,4:40PM,1600,15,Division,Denver,Broncos,Broncos,39.43,-105.01,56.0,{'value': 'Sunny'},3.0
464,2015-01-24,3:05PM,1500,14,ConfChamp,Denver,Broncos,Broncos,39.43,-105.01,64.0,{'value': 'Partly cloudy'},40.0
465,2015-01-24,6:42PM,1800,17,ConfChamp,Carolina,Panthers,Panthers,35.14,-80.50,33.0,{'value': 'Overcast'},100.0
466,2015-02-07,6:39PM,1800,17,SuperBowl,Denver,Broncos,Broncos,39.43,-105.01,58.0,{'value': 'Partly cloudy'},57.0