In [1]:
import pandas as pd
import requests
from pprint import pprint
import time as T
from datetime import datetime

In [2]:
table_1 = pd.read_csv("Table 1.csv")
table_2 = pd.read_csv("Table 2.csv")
table_3 = pd.read_csv("Table 3.csv")
table_4 = pd.read_csv("Table 4.csv")
table_5 = pd.read_csv("Table 5.csv")
table_6 = pd.read_csv("Table 6.csv")

In [3]:
table_1.head()

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0

In [4]:
merged = pd.concat([table_1,table_2,table_3,table_4,table_5,table_6], axis=0)
merged.head(25)

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
0,2008-09-04,7:08PM,1900,18,1,New York,Giants,Giants,40.43,-74.01,72.0,{'value': 'Clear'},0.0
1,2008-09-07,1:02PM,1300,12,1,Philadelphia,Eagles,Eagles,39.57,-75.07,82.0,{'value': 'Partly cloudy'},38.0
2,2008-09-07,1:02PM,1300,12,1,Miami,Dolphins,Jets,25.46,-80.12,59.0,{'value': 'Light rain shower'},97.0
3,2008-09-07,1:02PM,1300,12,1,New England,Patriots,Patriots,42.21,-71.04,82.0,{'value': 'Partly cloudy'},38.0
4,2008-09-07,1:02PM,1300,12,1,Pittsburgh,Steelers,Steelers,40.26,-80.00,72.0,{'value': 'Sunny'},14.0
5,2008-09-07,1:02PM,1300,12,1,Buffalo,Bills,Bills,42.54,-78.53,82.0,{'value': 'Partly cloudy'},38.0
6,2008-09-07,1:05PM,1300,12,1,Tennessee,Titans,Titans,36.09,-86.48,NaN,NaN,NaN
7,2008-09-07,1:06PM,1300,12,1,Baltimore,Ravens,Ravens,39.17,-76.37,82.0,{'value': 'Partly cloudy'},38.0
8,2008-09-07,4:15PM,1600,15,1,San Diego,Chargers,Panthers,32.43,-118.09,76.0,{'value': 'Partly cloudy'},29.0
9,2008-09-07,4:16PM,1600,15,1,Cleveland,Browns,Cowboys,41.30,-81.41,80.0,{'value': 'Sunny'},0.0
10,2008-09-07,4:16PM,1600,15,1,San Francisco,49ers,Cardinals,37.48,-122.24,61.0,{'value': 'Partly cloudy'},57.0
11,2008-09-07,8:23PM,2000,19,1,Indianapolis,Colts,Bears,39.46,-86.09,77.0,{'value': 'Clear'},16.0
12,2008-09-08,7:10PM,1900,18,1,Green Bay,Packers,Packers,44.30,-88.01,56.0,{'value': 'Light rain shower'},89.0
13,2008-09-08,10:22PM,2200,21,1,Oakland,Raiders,Broncos,37.47,-122.13,57.0,{'value': 'Patchy rain possible'},35.0
14,2008-09-14,1:00PM,1300,12,2,St. Louis,Rams,Giants,38.38,-90.11,94.0,{'value': 'Sunny'},2.0
15,2008-09-14,1:00PM,1300,12,2,Kansas City,Chiefs,Raiders,39.06,-94.37,77.0,{'value': 'Torrential rain shower'},66.0
16,2008-09-14,1:02PM,1300,12,2,Cincinnati,Bengals,Titans,39.06,-84.31,77.0,{'value': 'Torrential rain shower'},66.0
17,2008-09-14,1:03PM,1300,12,2,Washington,Redskins,Redskins,38.54,-77.01,94.0,{'value': 'Sunny'},2.0
18,2008-09-14,1:03PM,1300,12,2,Jacksonville,Jaguars,Bills,30.20,-81.40,64.0,{'value': 'Sunny'},0.0
19,2008-09-14,1:03PM,1300,12,2,Carolina,Panthers,Panthers,35.14,-80.50,80.0,{'value': 'Partly cloudy'},47.0
20,2008-09-14,4:05PM,1600,15,2,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate or heavy rain shower'},71.0
21,2008-09-14,4:06PM,1600,15,2,Seattle,Seahawks,49ers,47.36,-122.20,66.0,{'value': 'Sunny'},3.0
22,2008-09-14,4:15PM,1600,15,2,Denver,Broncos,Broncos,39.43,-105.01,78.0,{'value': 'Moderate or heavy rain shower'},48.0
23,2008-09-14,4:15PM,1600,15,2,New York,Jets,Patriots,40.43,-74.01,66.0,{'value': 'Sunny'},3.0
24,2008-09-14,4:15PM,1600,15,2,Arizona,Cardinals,Cardinals,33.27,-112.05,66.0,{'value': 'Sunny'},3.0

In [5]:
# Step one: fill in blanks for Tampa Bay

In [6]:
empty_locations = merged[merged.Latitude.isnull()]
empty_locations

,Full Date,Time,time_conv,time_index,Week,City,Home Team,Winner,Latitude,Longitude,Starting Game Temp (F),weatherDesc,cloudcover
20,2008-09-14,4:05PM,1600,15,2,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate or heavy rain shower'},71.0
44,2008-09-28,1:02PM,1300,12,4,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,90.0,{'value': 'Patchy rain possible'},46.0
62,2008-10-12,1:02PM,1300,12,6,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,84.0,{'value': 'Moderate or heavy rain shower'},37.0
2,10/19/08,8:23PM,2000,19,7,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,74.0,{'value': 'Light rain shower'},62.0
42,11/16/08,1:02PM,1300,12,11,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,86.0,{'value': 'Overcast'},90.0
67,11/30/08,1:02PM,1300,12,13,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,76.0,{'value': 'Sunny'},0.0
33,2008-12-21,1:02PM,1300,12,16,Tampa Bay,Buccaneers,Chargers,NaN,NaN,84.0,{'value': 'Sunny'},10.0
45,2008-12-28,1:02PM,1300,12,17,Tampa Bay,Buccaneers,Raiders,NaN,NaN,85.0,{'value': 'Sunny'},15.0
68,2009-09-13,1:03PM,1300,12,1,Tampa Bay,Buccaneers,Cowboys,NaN,NaN,86.0,{'value': 'Cloudy'},75.0
90,2009-09-27,1:00PM,1300,12,3,Tampa Bay,Buccaneers,Giants,NaN,NaN,91.0,{'value': 'Partly cloudy'},27.0
125,2009-10-18,1:00PM,1300,12,6,Tampa Bay,Buccaneers,Panthers,NaN,NaN,84.0,{'value': 'Patchy rain possible'},28.0
140,2009-10-25,1:06PM,1300,12,7,Tampa Bay,Buccaneers,Patriots,NaN,NaN,88.0,{'value': 'Partly cloudy'},37.0
162,2009-11-08,1:03PM,1300,12,9,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,91.0,{'value': 'Sunny'},10.0
184,2009-11-22,1:00PM,1300,12,11,Tampa Bay,Buccaneers,Saints,NaN,NaN,80.0,{'value': 'Sunny'},12.0
221,2009-12-13,1:00PM,1300,12,14,Tampa Bay,Buccaneers,Jets,NaN,NaN,86.0,{'value': 'Sunny'},9.0
263,2009-01-03,1:03PM,1300,12,17,Tampa Bay,Buccaneers,Falcons,NaN,NaN,77.0,{'value': 'Partly cloudy'},59.0
279,2010-09-12,1:02PM,1300,12,1,Tampa Bay,Buccaneers,Buccaneers,NaN,NaN,81.0,{'value': 'Moderate rain at times'},67.0
307,2010-09-26,1:03PM,1300,12,3,Tampa Bay,Buccaneers,Steelers,NaN,NaN,92.0,{'value': 'Patchy rain possible'},40.0

In [ ]:
#locations_list = ({'Franchise': ['Chicago', 'Green Bay', 'Arizona', 'Baltimore', 'Buffalo', 'Carolina', 'Cincinnati', 'Cleveland', 'Denver', 'Indianapolis', 'Jacksonville', 'Kansas City', 'Miami', 'New England', 'New York', 'Oakland', 'Philadelphia', 'Pittsburgh', 'St. Louis', 'San Diego', 'San Francisco', 'Seattle', 'Tampa Bay', 'Tennessee', 'Washington'], 'Latitude': [41.529998779296875, 44.29999923706055, 33.27000045776367, 39.16999816894531, 42.540000915527344, 35.13999938964844, 39.060001373291016, 41.29999923706055, 39.43000030517578, 39.459999084472656, 30.200000762939453, 39.060001373291016, 25.459999084472656, 42.209999084472656, 40.43000030517578, 37.470001220703125, 39.56999969482422, 40.2599983215332, 38.380001068115234, 32.43000030517578, 37.47999954223633, 47.36000061035156, 27.56999969482422, 36.09000015258789, 38.540000915527344], 'Longitude': [-87.37999725341797, -88.01000213623047, -112.05000305175781, -76.37000274658203, -78.52999877929688, -80.5, -84.30999755859375, -81.41000366210938, -105.01000213623047, -86.08999633789062, -81.4000015258789, -94.37000274658203, -80.12000274658203, -71.04000091552734, -74.01000213623047, -122.12999725341797, -75.06999969482422, -80.0, -90.11000061035156, -118.08999633789062, -122.23999786376953, -122.19999694824219, -82.2699966430664, -86.4800033569336, -77.01000213623047]})
#locations = pd.DataFrame(locations_list)
#locations = locations.round(2)

In [ ]:
empty_locations["Latitude"] = empty_locations["Latitude"].fillna(27.57)
empty_locations["Longitude"] = empty_locations["Longitude"].fillna(-82.27)

In [ ]:
filled_locations = empty_locations
filled_locations

In [ ]:
# titans and other teams with blank rows/pulls

In [ ]:
empty_pull = merged[merged.weatherDesc.isnull()]
empty_pull

In [ ]:
empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]] = empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]].fillna(0)
empty_pull

In [ ]:
empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]] = empty_pull[["Starting Game Temp (F)","weatherDesc","cloudcover"]].astype(int)
empty_pull.dtypes

In [ ]:
empty_pull["Full Date"] = empty_pull["Full Date"].str.replace('/','-')
#empty_pull["Full Date"] = pd.to_datetime(empty_pull["Full Date"], format="%Y-%m-%d")
empty_pull

In [ ]:
#test = "http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key=6cd0fcd19b014508966202712210906&q=36.09,-86.48&date=2008-09-21&tp=24&format=json"

In [ ]:
base_url = "http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key=6cd0fcd19b014508966202712210906&q=36.09,-86.48&date="
for index, row in empty_pull.iterrows():
    try:

        date = row["Full Date"]
        weather_url = f"{base_url},{date}&tp=24&format=json"
        weather_info = requests.get(weather_url).json()
        
        #print("------------")
        #pprint(weather_info)
        #print("------------")
        
        empty_pull.loc[index, "Starting Game Temp (F)"] = weather_info['data']['weather'][0]['hourly'][0]['tempF']
        empty_pull.loc[index, "weatherDesc"] = weather_info['data']['weather'][0]['hourly'][0]['weatherDesc']
        empty_pull.loc[index, "cloudcover"]= weather_info['data']['weather'][0]['hourly'][0]['cloudcover']
        
        #print("------------")
        #print(weather_info)
        #print("------------")
        T.sleep(.5)
        print(date)
    except (KeyError,IndexError):
        print("------------")
        print("interrupt asap")
        print(weather_url)
        print(index)
        print("------------")
        pass

In [ ]:
empty_pull

In [ ]:
# run API call last time for the blanks (mainly titans) - it will be for average of day.

In [ ]:
# Step 3 remove duplicates
merged = merged.drop_duplicates()
merged